spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yingx?CharacterEncoding=UFT-8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 4
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

elasticsearch:
  host: 127.0.0.1
  port: 9200
